### ISSUE TITLE
Broken link to the data

### ISSUE THREAD

**Issue by kuynzereb** [csimstu2/SPFN#1]
Hi @csimstu2,

when I try to download the provided dataset I get an error 404, so [the link](https://shapenet.cs.stanford.edu/media/minhyuk/spfn/data/spfn_traceparts.zip) to the data seems to be broken. Could you check it, please?

**Comment by lingxiaoli94** [comment]
Hi,

Thanks for bringing up this issue. Currently we are in the stage of checking all license issues before releasing the data. If that goes through we should be able to release the data this week.

**Comment by kuynzereb** [comment]
Ok, thank you for replying!
